version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node
    steps:
      - checkout

      - restore_cache:
          key: cache-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: cache-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          key: cache-yarn-{{ checksum "yarn.lock" }}
      - run: bin/yarn install
      - save_cache:
          key: cache-yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run: yarn run lint
      - run: bundle exec rubocop
      - run: bundle exec rspec
